# Generated by Django 5.2 on 2025-04-21 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_keys', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apikey',
            name='request_count',
        ),
        migrations.RemoveField(
            model_name='apikey',
            name='request_limit',
        ),
    ]
