# Generated by Django 5.2 on 2025-04-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramuser',
            options={'verbose_name': 'Telegram User', 'verbose_name_plural': 'Telegram Users'},
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('banned', 'Banned'), ('inactive', 'Inactive')], default='active', max_length=10),
        ),
        migrations.AddIndex(
            model_name='telegramuser',
            index=models.Index(fields=['user_id'], name='telegram_te_user_id_8111fa_idx'),
        ),
        migrations.AddIndex(
            model_name='telegramuser',
            index=models.Index(fields=['username'], name='telegram_te_usernam_cc492e_idx'),
        ),
        migrations.AddIndex(
            model_name='telegramuser',
            index=models.Index(fields=['is_active'], name='telegram_te_is_acti_cf4848_idx'),
        ),
        migrations.AddIndex(
            model_name='telegramuser',
            index=models.Index(fields=['last_seen'], name='telegram_te_last_se_b29bb2_idx'),
        ),
    ]
