# Generated by Django 5.2 on 2025-04-22 16:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0002_alter_telegramuser_options_telegramuser_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='last_reset_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='max_requests',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='request_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='telegramuser',
            index=models.Index(fields=['last_reset_at'], name='telegram_te_last_re_b1036d_idx'),
        ),
    ]
