# Generated by Django 5.2 on 2025-04-22 16:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0003_telegramuser_last_reset_at_telegramuser_max_requests_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramCommand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('command_type', models.CharField(choices=[('coin', 'Coin'), ('gold', 'Gold'), ('crypto', 'Crypto'), ('currency', 'Currency')], db_index=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tg_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commands', to='telegram.telegramuser')),
            ],
            options={
                'verbose_name': 'Telegram Command',
                'verbose_name_plural': 'Telegram Commands',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tg_user'], name='telegram_te_tg_user_2c8ec7_idx'), models.Index(fields=['command_type'], name='telegram_te_command_058905_idx'), models.Index(fields=['created_at'], name='telegram_te_created_457916_idx')],
            },
        ),
    ]
